### ISSUE TITLE
Create option to set world lighting/background

### ISSUE THREAD

**Issue by jacob-umich** [sc2umich-org/solids-vis-1#23]
## Background

We have implemented features that focus on animating and rending the subject matter, but what about the surrounding space. There are a few easily-to-implement options for setting a background. First, the background can be made a certain color or transparent, making light of the background color emit from it. Second, an image can be used as a background. Another option would be to create a separate series of objects to use as a background, but we will omit this option.

## Tasks
- [ ] Create a method to choose whether the background is transparent in the render
- [ ] create a method to set the background color and strength
- [ ] create a method to use an image as a background
