### ISSUE TITLE
Initialize the modeling environment for visualizing

### ISSUE THREAD

**Issue by jacob-umich** [sc2umich-org/solids-vis-1#4]
## Background

When blender starts a new model, it automatically generates a cube, light source, and a camera. This task requires us to clear any unnecessary objects, like the cube, and set up other factors in the environment, like lighting. These objects can be accessed through the bpy module

https://docs.blender.org/api/3.4/index.html

## Tasks
- [ ] remove the cube from starting scripts
- [ ] add options to adjust the lighting
- [ ] investigate other configuration options that might be good to set at this point, such as background.
- [ ] create tests for each configuration option and for the cube's removal

## Definition of done
the cube is successfully deleted and at least lighting and background configurations are added.
